# Generated by Django 3.2.7 on 2021-11-14 22:03

from django.db import migrations, models
import kanban.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('board', models.JSONField(default=kanban.models.board_default)),
            ],
        ),
        migrations.CreateModel(
            name='InvitedProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inviter', models.EmailField(max_length=100)),
                ('workspace_uid', models.UUIDField(editable=False)),
                ('portfolio_uid', models.UUIDField(editable=False)),
                ('project_uid', models.UUIDField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_name', models.CharField(max_length=50)),
                ('portfolio_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('pined_portfolio', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('project_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('invited_users', models.JSONField(null=True)),
                ('project_description', models.CharField(max_length=250)),
                ('pined_project', models.BooleanField(default=False)),
                ('agile_framwork', models.CharField(choices=[('Scrum', 'Scrum'), ('Kanban', 'Kanban')], default='Kanban', max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace_name', models.CharField(max_length=100)),
                ('workspace_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('work_email', models.EmailField(max_length=100)),
            ],
        ),
    ]
