# Generated by Django 3.2.7 on 2021-10-11 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('name', 'portfolio')},
        ),
        migrations.AlterUniqueTogether(
            name='portfolio',
            unique_together={('portfolio_name', 'portfolio_user')},
        ),
    ]
