# Generated by Django 3.2.7 on 2021-11-14 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kanban', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='workspace_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanban.portfolio'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanban.workspace'),
        ),
        migrations.AddField(
            model_name='invitedprojects',
            name='inviter_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='kanban.project'),
        ),
        migrations.AddField(
            model_name='invitedprojects',
            name='iuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='board',
            name='prj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanban.project'),
        ),
        migrations.AlterUniqueTogether(
            name='workspace',
            unique_together={('workspace_name', 'workspace_user')},
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('name', 'portfolio')},
        ),
        migrations.AlterUniqueTogether(
            name='portfolio',
            unique_together={('portfolio_name', 'workspace')},
        ),
        migrations.AlterUniqueTogether(
            name='invitedprojects',
            unique_together={('iuser', 'inviter', 'workspace_uid', 'portfolio_uid', 'project_uid')},
        ),
        migrations.AlterUniqueTogether(
            name='board',
            unique_together={('name', 'prj')},
        ),
    ]
