# Generated by Django 3.2.7 on 2021-10-05 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='kanbanboard',
            unique_together={('name', 'portfolio')},
        ),
    ]
