# Generated by Django 3.2.7 on 2021-10-15 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='product_owner',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='project',
            name='scrum_master',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
