# Generated by Django 3.2.7 on 2021-11-16 12:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kanban', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invitedprojects',
            unique_together={('iuser', 'inviter_project')},
        ),
        migrations.RemoveField(
            model_name='invitedprojects',
            name='inviter',
        ),
    ]
