# Generated by Django 3.2.7 on 2021-10-05 12:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kanban', '0002_alter_kanbanboard_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='portfolio',
            unique_together={('portfolio_name', 'portfolio_user')},
        ),
    ]
