# Generated by Django 3.2.7 on 2021-11-23 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0003_auto_20211116_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardActivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_user_email', models.EmailField(max_length=100)),
                ('activity_description', models.CharField(max_length=250)),
                ('activity_date', models.DateTimeField(auto_now_add=True)),
                ('activity_type', models.CharField(max_length=50)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanban.board')),
            ],
        ),
    ]
