# Generated by Django 3.2.7 on 2021-10-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0003_alter_portfolio_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='id_col',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='boardcol',
            unique_together={('board', 'col_name')},
        ),
    ]
