# Generated by Django 3.2.7 on 2021-10-05 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0004_auto_20211005_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kanbanboard',
            name='agile_framwork',
        ),
    ]
