# Generated by Django 3.2.7 on 2021-11-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0004_boardactivities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardactivities',
            name='activity_type',
            field=models.SlugField(),
        ),
    ]
