# Generated by Django 3.2.7 on 2021-10-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0005_remove_kanbanboard_agile_framwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='id_col',
            field=models.BigIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('col', 'id_col')},
        ),
    ]
