# Generated by Django 3.2.7 on 2021-10-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0006_auto_20211005_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanbanboard',
            name='agile_framwork',
            field=models.CharField(choices=[('Scrum', 'Scrum'), ('Kanban', 'Kanban')], default='Kanban', max_length=6),
        ),
    ]
