# Generated by Django 3.2.7 on 2021-11-28 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0006_projectonlineusers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectOnlineUsers',
        ),
    ]
