# Generated by Django 3.2.7 on 2021-10-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0007_kanbanboard_agile_framwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanbanboard',
            name='project_description',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
