# Generated by Django 3.2.7 on 2021-12-06 19:32

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0009_rename_online_status_projectonlineusers_is_online'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectGroupeChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auditor', models.EmailField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('attachments', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=600), blank=True, null=True, size=None)),
                ('prj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanban.project')),
            ],
        ),
    ]
