# Generated by Django 3.2.7 on 2021-10-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0009_auto_20211007_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='pined_portfolio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='pined_project',
            field=models.BooleanField(default=False),
        ),
    ]
