# Generated by Django 3.2.7 on 2021-12-06 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0011_alter_projectgroupechat_prj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectgroupechat',
            name='prj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanban.project'),
        ),
    ]
