# Generated by Django 3.2.7 on 2021-12-09 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0014_alter_projectgroupechat_auditor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectOnlineUsers',
        ),
    ]
