# Generated by Django 3.2.7 on 2021-12-23 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0018_wiki'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wiki',
            old_name='project',
            new_name='wiki_project',
        ),
    ]
