# Generated by Django 3.2.7 on 2021-09-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vifApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
