# Generated by Django 3.2.7 on 2021-10-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vifApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.URLField(default='https://yt3.ggpht.com/ytc/AKedOLTe9zzL4WQB8f45LqYCzx8K6Ww-df74yiKKI2ZC=s88-c-k-c0x00ffffff-no-rj', max_length=600),
        ),
    ]
