# Generated by Django 3.2.7 on 2021-09-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vifApp', '0002_auto_20210925_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
