# Generated by Django 3.2.7 on 2021-09-17 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vifApp', '0002_usernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='notification_from',
            field=models.CharField(default='Ayoub', max_length=200),
            preserve_default=False,
        ),
    ]
