# Generated by Django 3.2.7 on 2021-11-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vifApp', '0002_usernotification_notification_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Busy', 'Busy'), ('Do not disturb', 'Do not disturb'), ('Away', 'Away')], default='Available', max_length=15),
        ),
    ]
