# Generated by Django 3.2.7 on 2021-10-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vifApp', '0003_auto_20211014_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.URLField(default='https://vifbox.org/api/media/default.jpg', max_length=600),
        ),
    ]
