# Generated by Django 3.2.7 on 2021-09-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vifApp', '0003_usernotification_notification_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.CharField(default='url_to_image_hghghghgh.png', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='profile_title',
            field=models.CharField(default='software devoloper', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usernotification',
            name='notification_url',
            field=models.CharField(default='notification_url.com', max_length=200),
            preserve_default=False,
        ),
    ]
