# Generated by Django 3.2.7 on 2021-12-17 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vifApp', '0004_alter_user_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='social_id',
        ),
    ]
