# Generated by Django 3.2.7 on 2021-10-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vifApp', '0006_alter_user_social_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='vifbox user', max_length=50),
            preserve_default=False,
        ),
    ]
